### ISSUE TITLE
Blocks Malwarebytes Updates?

### ISSUE THREAD

**Issue by hl2guide** [marcusminus/Orthrus-BlockList#2]
Blocking **telemetry.malwarebytes.com** seems to block/fail all Malwarebytes updates, for me at least.

**Comment by marcusminus** [comment]
Malwarebytes is a legitimate company and updated security software/threat db is a priority. Domain removed from lists.

Report in official Malwarebytes forum about privacy issues: https://forums.malwarebytes.com/topic/237372-malwarebytes-sending-telemetry-despite-option-is-turned-off/
