### ISSUE TITLE
blocklist

### ISSUE THREAD

**Issue by ghost** [marcusminus/Orthrus-BlockList#3]
Hi,
@marcusminus 
Can you please add these to the blockade?
for blocklist.txt
```
dcs.ettoday.net
adv.ettoday.net
@@||s.yimg.com^
```
The following are hoped to be removed:
```
ad.ettoday.net
dable.io
popin.cc
api.popin.cc
static.dable.io
```
Because important content will not be displayed.

thanks.

**Comment by marcusminus** [comment]
b302cc6e8ac015449374507b42c168bafdf7c1f3
ef70dabcbd2b03036c611a849513d1926373cac1
98fad05fb52fe7f14812a89b1437654636f1a703

**Comment by marcusminus** [comment]
Commits:

b302cc6e8ac015449374507b42c168bafdf7c1f3
ef70dabcbd2b03036c611a849513d1926373cac1
98fad05fb52fe7f14812a89b1437654636f1a703
